receivers:
  otlp:
    protocols:
      grpc: # on port 4317

processors:
  batch:

exporters:
  logging:
    loglevel: debug 

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
